# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 1800 # 30 minutes

#================#
# CentOS Nodes   #
#================#

  (1..3).each do |i|  
    config.vm.define "ansible-node0#{i}" do |cfg|    
      cfg.vm.box = "centos/7"             
      cfg.vm.provider "virtualbox" do |vb|      
        vb.name = "Ansible-Node0#{i}"        
        vb.customize ["modifyvm", :id, "--groups", "/ansible"]
      end
      cfg.vm.host_name = "ansible-node0#{i}"  
      cfg.vm.network "private_network", ip: "192.168.56.1#{i}" 
      cfg.vm.network "forwarded_port", guest: 22, host: "6001#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
    end
  end

#================#
# Ubuntu nodes   #
#================#
  (4..6).each do |i| 
    config.vm.define "ansible-node0#{i}" do |cfg|    
      cfg.vm.box = "ubuntu/trusty64"             
      cfg.vm.provider "virtualbox" do |vb|      
        vb.name = "Ansible-Node0#{i}" 
        vb.customize ["modifyvm", :id, "--groups", "/ansible"]
        vb.cpus = 2
        vb.memory = 2048       
      end
      cfg.vm.host_name = "ansible-node0#{i}"  
      cfg.vm.network "private_network", ip: "192.168.56.1#{i}" 
      cfg.vm.network "forwarded_port", guest: 22, host: "6001#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    end
  end

#================#
# Ansible Server #
#================#
  config.vm.define "ansible-server" do |cfg|    
    cfg.vm.box = "centos/7"             
    cfg.vm.provider "virtualbox" do |vb|      
      vb.name = "Ansible-Server"        
    end
    cfg.vm.host_name = "ansible-server"  
    cfg.vm.network "private_network", ip: "192.168.56.10" 
    cfg.vm.network "forwarded_port", guest:22, host: 60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y"
    cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
    cfg.vm.provision "file", source: "auto_pass.yml", destination: "auto_pass.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook auto_pass.yml", privileged: false
  end
end